export const ADD_INGREDIENT = "ADD-INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SHOW_ERROR_FETCHING_INGREDIENTS = "SHOW_ERROR_FETCHING_INGREDIENTS";

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_BURGER_INIT = "PURCHASE_BURGER_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const SET_ORDERS = "SET_ORDERS";
export const SHOW_ERROR_FETCHING_ORDERS = "SHOW_ERROR_FETCHING_ORDERS";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
