export const ADD_INGREDIENT = "ADD-INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SHOW_ERROR_FETCHING_INGREDIENTS =
    "SHOW_ERROR_FETCHING_INGREDIENTS";
